- src/common.jl
- src/metrics.jl
- src/wmetrics.jl
- test/test_dists.jl
The goal of this pull request is to allow AbstractArrays rather than just AbstractVectors in `metrics` and `wmetrics`. To allow this, I follow a recent pull request by @timholy  in Base #13460.
Since the loop is slightly more verbose, I ended up refractoring the code. There is no supplementary allocation compared to the current situation (i.e. @time macro gives the same allocation).
Moreover, I did two changes:
- Chebyshev now relies on the `max` function. If `max(0, NaN)` were to be changed to `NaN` at some point in Base, this will directly pass through.
- Type instability in  `JSDivergence` is suppressed
Now I'm unclear on something. While some norms are initiated to `zero(eltype(a))`, most of the distances are intiated to 0.0. I'm not sure why. Should not `chebyshev([1, 3], [1, 4])` …
> Allow Abstract Arrays

- src/bhattacharyya.jl
- src/common.jl
- src/mahalanobis.jl
- src/metrics.jl
- src/wmetrics.jl
- test/runtests.jl
- test/test_dists.jl
This dissapeared in the latest refactoring and makes a big difference.
With
```jl
function test()
a = rand(100)
b = rand(100)
E = Euclidean()
@time for i = 1:10^7
evaluate(E, a, b)
end
end
function test32()
a = rand(Float32, 100)
b = rand(Float32, 100)
E = Euclidean()
@time for i = 1:10^7
evaluate(E, a, b)
end
end
```
I get on master:
```jl
julia> test32()
0.823266 seconds
julia> test()
0.801979 seconds
```
and with PR:
```jl
julia> test()
0.409450 seconds
julia> test32()
0.261282 seconds
```
> Add back @simd to evaluate

- src/generic.jl
- src/mahalanobis.jl
- src/metrics.jl
Ref #28, fixes #28
Problem was that the `result_type` in `generic` had different signatures than the ones in `metric` so the specialized `result_types` were never used when `pairwise` was used. This unifies the `result_type` signatures.
Benchmark:
```jl
N = 10000;
dim = 25;
data = rand(Float32, dim, N);
query = rand(Float32, dim, N);
julia> @time pairwise(SqEuclidean(), data, query);
2.435364 seconds (37 allocations: 763.017 MB, 0.34% gc time)
julia> @time pairwise(SqEuclidean(), data, query);
0.222634 seconds (31 allocations: 381.547 MB, 0.88% gc time)
```
> unify the result_type method

- src/bhattacharyya.jl
Caught by the "method overwritten" warning in Julia v0.5.
> Typo fix: BhattacharyyaDist -> HellingerDist

- src/Distances.jl
- src/common.jl
- src/generic.jl
Julia-v0.5 has renamed `slice` to `view`.  We need this change for dependent packages.
> Add support for julia-v0.5 slice->view change

- README.md
- src/metrics.jl
- test/test_dists.jl
On master we have this:
```julia
julia> using Distances
julia> X = [0.1 0.2; 0.3 0.4; -0.1 -0.1]
3×2 Array{Float64,2}:
0.1   0.2
0.3   0.4
-0.1  -0.1
julia> pd = pairwise(Euclidean(), X, X)
2×2 Array{Float64,2}:
7.45058e-9  0.141421
0.141421    0.0     
```
Obviously the diagonal entries of `pd` should be 0. Here it's not because of the strategy (chosen for efficiency) to calculate dot products and then compute the square-distance by `sa + sb - 2*r`. This PR recalculates the distance by `\sum (ai-bi)^2` when the gap between the points is below some threshold. It should be non-breaking, because the fallback threshold is 0.
> Add a precision threshold to Euclidean

- README.md
- src/bhattacharyya.jl
- src/mahalanobis.jl
- src/metrics.jl
- test/bench_colwise.jl
- test/bench_pairwise.jl
- test/test_dists.jl
I've noticed while working on #58 that there is a fairly ad hoc testing of whether the subtyping is correct for the distance measures defined here - there is much testing of equality to zero for self-distances, but not symmetry (for `SemiMetric`s) and the triangle inequality (for `Metric`s). I've introduced a test `@test_metricity`, that checks what each distance is a subtype of and tests the appropriate conditions.
There is now a systematic test for each distance measure to check it does not overclaim it's "metricity" (it can't check for underclaiming, but that is a less serious problem). This exposed a series of problems to do with floating point rounding errors for `CorrDist`, `CosineDist` and `RenyiDivergence`. This kind of issue has been identified before (e.g. #13), which I have now …
> Tests for correct Pre/Semi/Metric subtyping

- src/Distances.jl
- src/common.jl
- src/generic.jl
- src/mahalanobis.jl
- src/metrics.jl
- src/wmetrics.jl
- test/F64.jl
- test/runtests.jl
- test/test_dists.jl
Also tests it by defining a new number type that is a subtype of Real and calling everything.
Replaces #72.
> relax metrics to Real

- src/haversine.jl
- test/test_dists.jl
This PR takes care of well-known floating point errors in the haversine formula. It was originally captured here: https://github.com/juliohm/GeoStats.jl/issues/14
> Handle floating point errors in Haversine distance

- benchmark/benchmarks.jl
We updated the interface for `Haversine` and forgot to update the benchmarks accordingly. This PR fixes the issue.
> Fix call to Haversine ctor in benchmark scripts

- README.md
- src/metrics.jl
- test/test_dists.jl
Currently `chisq_dist([0.], [0.])` would generate `NaN`, but we can [continuously] define it (0, 0) to be 0.
> Fix ChiSq distance around zero

- README.md
- src/common.jl
- src/generic.jl
- src/mahalanobis.jl
- src/metrics.jl
- src/wmetrics.jl
- test/test_dists.jl
This allows specifying whether observations are stored as columns (`dims=2`) or as rows (`dims=1`).
All functions are still written internally to perform computations over columns, computations over rows are supported by calling transpose on the matrices.
Add a deprecation to require specifying explicitly `dims=1` or `dims=2`: contrary to this package, other implementations most frequently default to `dims=1`, and even in Julia the `cov` and `cor` functions default to `dims=1`.
Fixes https://github.com/JuliaStats/Distances.jl/issues/35.
> Add dims argument to pairwise

- Project.toml
It's not required and makes TravisCI fail if not in sync with tagged version.
> Remove version from Project.toml

- src/generic.jl
Excerpt from https://github.com/JuliaStats/Distances.jl/pull/123.
> Add docstrings for pairwise and pairwise!

- src/metrics.jl
Fixes #113.
I'm not exactly sure what the problem was, because the error was happening during compilation with PackageCompiler but not when simply loading the module.  In any case, using `@doc` for getting the docstring led to trying to look up docstring at parse time in a context where `RenyiDivergence` was undefined, and this change shifts the lookup to happen during evaluation of the module definition.
> Get docstring without @doc to avoid error when compiling

- src/metrics.jl
`rmsd(x, y) / (maximum(x) - minimum(x))` can't swap(`nrmsd(x,y)!=nrmsd(y,x)`), so it isn't a `SemiMetric`, this would introduce problems calling `pairwise`
> correct NormRMSDeviation type

- src/common.jl
- src/metrics.jl
- src/wmetrics.jl
- test/test_dists.jl
When I started working on this PR, my intention was to fix https://github.com/JuliaStats/Distances.jl/issues/130. Actually only the changes in https://github.com/devmotion/Distances.jl/blob/promote_op/src/common.jl#L115 and https://github.com/devmotion/Distances.jl/blob/promote_op/src/wmetrics.jl#L46 are needed to be able to run successfully
```julia
using Distances, Tracker
Tracker.gradient(x -> sum(pairwise(WeightedSqEuclidean(x), [3 5; 4 6]; dims = 2)), [1, 2])
y, back = Tracker.forward(x -> sum(pairwise(WeightedSqEuclidean([1,2]), x; dims = 2)), [3 5; 4 6])
back(1)
```
BTW, I don't know why but trying to execute
```julia
Tracker.gradient(x -> sum(pairwise(WeightedSqEuclidean([1, 2]), x; dims = 2)), [3 5; 4 6])
```
yields the error message
```julia
ERROR: MethodError: Cannot `convert` …
```
> Loosen type annotations and fix https://github.com/JuliaStats/Distances.jl/issues/130

- src/generic.jl
- src/mahalanobis.jl
- src/metrics.jl
- src/wmetrics.jl
The essence of `result_type` is based on the `eltype(a)`, and `result_type(::PreMetric, ::AbstractArray, ::AbstractArray)` only serves as an convenient method.
There are no functionality changes in this commit, only to reorganize the codes to ease future development.
---
For example, in `ImageDistances.jl`, we can easily extend `result_type` to `Colorant` types if we dispatch on `Type`:
```julia
for (ATa, ATb) in ((AbstractGray, AbstractGray),
(AbstractGray, Number      ),
(Number      , AbstractGray),
(PromoteType , PromoteType )) # Union{FixedPoint, Bool}
@eval function result_type(dist::PreMetric, a::Type{Ta}, b::Type{Tb}) where {Ta<:$ATa, Tb<:$ATb}
T1 = eltype(floattype(Ta)) # Gray{N0f8} -> Float32
T2 = eltype(floattype(Tb))
result_type(dist, T1, T2)
end
end
```
In the meantime, …
> rework result_type

- README.md
- src/bhattacharyya.jl
- src/bregman.jl
- src/generic.jl
- src/haversine.jl
- src/mahalanobis.jl
- src/metrics.jl
- src/wmetrics.jl
- test/runtests.jl
- test/test_dists.jl
This PR is related to #22, one can easily rename `evaluate` later if we reach a consensus.
By moving implementations into functor, `evaluate` now is simply a really thin wrapper here; `evaluate` is limited only in `generic.jl` now (line 24). 
This reduces the possibility of meeting method ambiguity introduced by inconsistent type specification. For example, the implementation of `CorrDist` is cleaner.
Another change is the new usage `dist(x, y)`, e.g., `Euclidean()(x, y)`.
P.S.
[1] Vscode auto-formats some codes here and I commit it as well.
[2] For `ImageDistances.jl`, it will be much easier to extend to `Colorant` elements without getting lost in method ambiguity and dispatch orders 😄 
cc: @andreasnoack @KristofferC @ararslan
> move implementations into type overloading (aka. functor)

- src/metrics.jl
As discussed in https://github.com/JuliaStats/Distances.jl/pull/150#issuecomment-541606075, this allows for dispatching on `Union*Metric` types, and should facilitate hooking into the `eval_***` and `parameters` business.
> turn UnionMetrics into types

- README.md
Add a sentence on how the types `SemiMetric` and `Metric` does not include positive definiteness as in the mathematical definition. It is possible for an object of these types to have  `x != y` and `d(x, y) = 0`.
This follows the discussion of #153.
> Comment on how type hierarchy differs from maths definitions

- Project.toml
- src/common.jl
- src/metrics.jl
- test/runtests.jl
- test/test_dists.jl
Closes #106. Closes #93.
The logic in the `UnionMetric`'s `_evaluate` wasn't able to distinguish the case when one array had offset indices. But I'm not sure if the logic here is too strict. I don't see any slowdown, though benchmarking is a bit nontrivial. I've used this for benchmarking:
```julia
using Distances, OffsetArrays, BenchmarkTools
for m in (2, 10, 30)
x, y, p = rand(m), rand(m), rand(m)
d = Euclidean()
dp = PeriodicEuclidean(p)
@btime $d($x, $y);
@btime $dp($x, $y);
end
```
Timings vary a bit, but I don't see a clear pattern of regression. Also, the infamous benchmark from #107 is clearly won by `colwise`.
Moreover
```julia
julia> using Distances, OffsetArrays
julia> x, y = rand(10), rand(10)
([0.02801362061758983, 0.8939414820779741, 0.711232152659703, 0.9910084998815372, …
```
> Enhancements: allow OffsetArrays and integer arrays in CosineDist

- Project.toml
- src/mahalanobis.jl
- test/test_dists.jl
Fixes negative values in the pairwise computations with SqMahalanobis, in the same way as done for the (weighted) (Sq)Euclidean distances (https://github.com/JuliaStats/Distances.jl/pull/161) and CosineDist.
On master:
```julia
julia> using Distances
julia> a = [0.3 0.3 + eps()]
1×2 Array{Float64,2}:
0.3  0.3
julia> pairwise(SqMahalanobis(ones(1, 1)), a; dims = 2)
2×2 Array{Float64,2}:
0.0          -2.77556e-17
-2.77556e-17   0.0
julia> pairwise(SqMahalanobis(ones(1, 1)), a, a; dims = 2)
2×2 Array{Float64,2}:
0.0          -2.77556e-17
-2.77556e-17   0.0
```
With this PR:
```julia
julia> using Distances
julia> a = [0.3 0.3 + eps()]
1×2 Array{Float64,2}:
0.3  0.3
julia> pairwise(SqMahalanobis(ones(1, 1)), a; dims = 2)
2×2 Array{Float64,2}:
0.0  0.0
0.0  0.0
julia> …
```
> Fix negative values in the pairwise computations of SqMahalanobis

- Project.toml
- src/metrics.jl
#150 has unfortunately broken the glue code in ImageDistances because it specializes the `result_type` for `UnionMetrics` without defining the method for `Type`.
https://github.com/JuliaStats/Distances.jl/blob/44036b573ec85287022f4368c4e1e279698bd031/src/generic.jl#L35
This PR adds these two methods:
```julia
result_type(dist::UnionMetrics, ::Type{Ta}, ::Type{Tb}, ::Nothing)
result_type(dist::UnionMetrics, ::Type{Ta}, ::Type{Tb}, p)
```
and https://github.com/JuliaImages/ImageDistances.jl/pull/46 gets fixed by this.
> simplify result_type on UnionMetrics

- Project.toml
- src/mahalanobis.jl
- test/test_dists.jl
This closes #181.
Would be good to accept AbstractMatrix as input to Mahalanobis
Otherwise, it'd not accept a StaticMatrix input
Made a simple adjust and tested here with a StaticMatrix. Working nice
> Change Mahalanobis input to AbstractMatrix

- src/Distances.jl
- src/bhattacharyya.jl
- src/bregman.jl
- src/common.jl
- src/generic.jl
- src/haversine.jl
- src/metrics.jl
- test/test_dists.jl
This adds support for iterable objects as arguments to `evaluate`,(EDIT: and `pairwise` and `colwise`). ~~I haven't touched pair- and colwise stuff, because that is (partially/completely?) addressed by #188.~~
Closes #187. Closes #162. Closes #165. Closes #152. Closes #190. Closes #192. Closes #188.
> Allow generators and iterators

- README.md
- src/haversine.jl
I don't think it should be necessary to look up the radius of Earth every time one wants to use the Haversine formula, so I've added the equatorial radius of Earth in meters as a default. I hope most imperial unit users will agree that metric is a reasonable default for scientific libraries. Of course Earth has different radii depending on where it is measured, as it isn't a perfect sphere. Uses sensitive to this should use more specific values. FYI this same default value is used in R. source https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html
> add default value of Earth's radius to Haversine

- Project.toml
- src/haversine.jl
- src/metrics.jl
- test/F64.jl
- test/runtests.jl
- test/test_dists.jl
Closes #201. Indeed, there is no reason why in general the temporary variable should have the same type/unit as the final result. Funnily, this added flexibility leads to a significant gain in performance in special cases where the types differ:
```julia
julia> using Distances, BenchmarkTools
julia> x = rand(1:5, 100);
julia> y = rand(1:5, 100);
julia> @btime euclidean($x, $y);
95.578 ns (0 allocations: 0 bytes) # master
33.965 ns (0 allocations: 0 bytes) # this PR
```
We need to mimick the `result_type` scheme once more, but the added code is not much. Pretty much all the metrics are covered, except those that involve a `log`, the `Mahalanobis` family, `Bregman`. ~~I need to check if `haversine` works with `°`.~~ EDIT: it does now.
> Allow unitful data points

- Project.toml
- README.md
- benchmark/benchmarks.jl
- src/common.jl
- src/metrics.jl
I started fixing the badges, and soon realized the README could use a little clean-up. Now it mentions the iterator-interface. I wonder whether we should keep the colwise benchmarks. After all, few metrics have a specialized implementation, so we do have a "simple loop implementation", and the speed-up shown results actually from using views in the generic methods. That's something that a user implementing her/his own naive loop might as well have used, so the real benefit from specialized methods is restricted to the [Sq]Mahalanobis and the `CorrDist` metrics. We could shorten the colwise benchmark to those that have a specialized method. Similarly for `pairwise`: the "competitor" doesn't use views. Alternatively, we could include the views in the simple loop competitors, and showcase …
> Clean up README

- Project.toml
- src/generic.jl
- src/haversine.jl
- src/metrics.jl
- test/test_dists.jl
Fixes #210, fixes #209.
It seems very hard to include a generic fallback à la `result_type(...) = Float64` again. So, the fix to #209 is to handle the `Missing` case explicitly, and the fix to #210 is to insist that a `result_type` method be given for "exotic" metrics that cannot handle `Number` arguments, and so we do it for `Haversine` and `Spherical_Angle`.
> Fix result_type issues

- Project.toml
- src/Distances.jl
This will allow StatsBase to define fallback methods
for these without conflicting with Distances.
> Import `pairwise` and `pairwise!` from StatsAPI

- README.md
It looks like there was a copy-paste typo in the README where JSDivergence was defined. It had `p` listed twice and no `q` in the definition.
> fix typo in readme definition of JSDivergence

- Project.toml
- README.md
- src/Distances.jl
- src/deprecated.jl
- src/generic.jl
- src/mahalanobis.jl
- src/metrics.jl
- test/test_dists.jl
This PR fixes https://github.com/JuliaStats/Distances.jl/issues/238 and deprecates `pairwise!(r, dist, a[, b])` in favour of `pairwise!(dist, r, a[, b])` which is consistent with StatsAPI and StatsBase.
It seemed natural to keep `colwise!` consistent with `pairwise!`, and hence I also deprecated `colwise!(r, dist, a, b)` in favour of `colwise!(dist, r, a, b)`.
> Change signature of `pairwise!` and `colwise!`

- Project.toml
- ext/ChainRulesCoreExt.jl
- ext/DistancesChainRulesCoreExt.jl
- test/chainrules.jl
- test/runtests.jl
This PR proposes to add a weak dependency on ChainRulesCore on Julia versions with support for extensions (i.e., Julia >= 1.9).
This would fix https://github.com/JuliaStats/Distances.jl/issues/172 (and https://github.com/FluxML/Zygote.jl/issues/1365) without affecting load and compilation times for users that do not load ChainRulesCore.
The initial set of reverse-mode rules in this PR covers the existing rules in Zygote and hence could replace these in Julia >= 1.9: Zygote could, e.g., wrap the Requires-block for Distances in a `if !isdefined(Base, :get_extension)` conditional.
The implementation in this PR is different from the code in https://github.com/FluxML/Zygote.jl/pull/923 since tests fail with the rules in the Zygote PR (e.g., due to type inference issues).
The rules in this PR …
> Add weak dependency on ChainRulesCore

- Project.toml
- README.md
- src/Distances.jl
- src/generic.jl
- src/metrics.jl
This new type will allow third-party packages to differentiate Minkowski metrics at the type level. It will also allow third-party packages to implement their own Minkowski metrics.
A practical example of a package that could use this new abstract type is NearestNeighbors.jl, which is currently using a union type for this purpose:
https://github.com/KristofferC/NearestNeighbors.jl/blob/master/src/kd_tree.jl#L1
With this new type NearestNeighbors.j could use Minkowski metrics defined in any package.
> Add `MinkowskiMetric` abstract type

- README.md
In  machine learning, distances are often computed with heterogeneous tables (e.g., kernel methods). This link can save users of Distances.jl a ton of time reinventing the wheel.
> Add link to TableDistances.jl
